version: '3'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - './init_sql:/docker-entrypoint-initdb.d'
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: test
    ports:
      - 43306:3306